registered_cameras: &registered_cameras
  - 192.168.4.101
  - 192.168.4.102
  - 192.168.4.105
  - 192.168.4.109
  - 192.168.4.99
  - 192.168.4.113
  - 192.168.4.114
  - 192.168.4.115
  - 192.168.4.116

parts:
  49:
    car_type: 'Tharu XR'
    Part_num: "22D 817 111 A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.3
  140: # test ok
    car_type: 'Tharu XR'
    Part_num: "22D 827 159"
    cameras: *registered_cameras
    shuttle_sensor_type: 2
    trigger_delay: 0.4
  142: # test ok
    car_type: 'Tharu XR'
    Part_num: "22D 809 605A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.4
  143: # test ok
    car_type: 'Tharu XR'
    Part_num: "22D 809 606A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.4

  50: # test ok
    car_type: 'Passat B8'
    Part_num: "3GB 817 111 A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.3
  60:
    car_type: 'Passat B8'
    Part_num: "3GB 827 106A 159A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.4
  76: # test ok
    car_type: 'Passat B8'
    Part_num: "3GB 809 605"
    cameras: *registered_cameras
    shuttle_sensor_type: 2
    trigger_delay: 0.45
  77: # test ok
    car_type: 'Passat B8'
    Part_num: "3GB 809 606"
    cameras: *registered_cameras
    shuttle_sensor_type: 1
    trigger_delay: 0.4


  120: # test ok
    car_type: 'Passat B9'
    Part_num: "3JG 809 605"
    cameras: *registered_cameras
    shuttle_sensor_type: 2
    trigger_delay: 0.4
  121: # test ok
    car_type: 'Passat B9'
    Part_num: "3JG 809 606"
    cameras: *registered_cameras
    shuttle_sensor_type: 1
    trigger_delay: 0.4
  128:
    car_type: 'Passat B9'
    Part_num: "3JG 827 106 159"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.4
  129:
    car_type: 'Passat B9'
    Part_num: "3JG 817 111 A"
    cameras: *registered_cameras
    shuttle_sensor_type: 0
    trigger_delay: 0.3
